//! Cross-implementation parity: the Rust SDK and the TypeScript SDK must
//! produce and consume the same artifact bytes.
//!
//! The fixture `fixtures/artifact_ed25519.json` was generated by the
//! TypeScript SDK (branch `feat/branching-sdk`) with a fixed seed
//! (`[7u8; 32]`), nonce (`[0u8; 32]`), and an inert op (no fee payer):
//! `serializeArtifact(vectorEd25519([7;32]).authorize([0;32], []))`.
//!
//! Because Ed25519 signing is deterministic, byte-identical output proves the
//! advance digest, the signature, and the JSON wire format all match across
//! the two implementations — not just that the formats are structurally
//! similar.
#![cfg(feature = "ed25519")]

use vector_core::{deserialize_artifact, serialize_artifact, verify_artifact, Ed25519, Op, Vector};

const TS_FIXTURE: &str = include_str!("fixtures/artifact_ed25519.json");

#[test]
fn rust_consumes_a_genuine_ts_artifact() {
    let json = TS_FIXTURE.trim_end();

    // Rust deserializes a real TS-produced artifact …
    let art = deserialize_artifact(json).expect("deserialize TS artifact");
    // … verifies the TS-produced signature offline …
    assert!(
        verify_artifact(&art).expect("known scheme"),
        "TS artifact failed Rust verify"
    );
    // … and re-serializes it byte-identically.
    assert_eq!(
        serialize_artifact(&art),
        json,
        "Rust re-serialization differs from TS"
    );
}

#[test]
fn rust_reproduces_the_ts_artifact_bit_for_bit() {
    // Same seed + nonce + inert op as the TS fixture. Deterministic Ed25519
    // means an identical signature, so the whole artifact — digest, layout,
    // and JSON — must be byte-identical to what TS produced.
    let v = Vector::new(Ed25519::from_seed(&[7u8; 32]));
    let art = v.authorize(&[0u8; 32], Op::Inert);
    assert_eq!(serialize_artifact(&art), TS_FIXTURE.trim_end());
}
