//! Cross-implementation parity: the Rust SDK and the TypeScript SDK must
//! produce and consume the same artifact bytes.
//!
//! Each `fixtures/artifact_<scheme>.json` was generated by the TypeScript SDK
//! (branch `feat/branching-sdk`) with a fixed seed (`[7u8; 32]`), nonce
//! (`[0u8; 32]`), and an inert op (no fee payer):
//! `serializeArtifact(vector<Scheme>([7;32]).authorize([0;32], []))`.
//!
//! Ed25519, secp256k1, and EIP-191 all sign deterministically (EdDSA /
//! RFC-6979 ECDSA), so byte-identical output proves the advance digest, the
//! signature, and the JSON wire format all match across the two
//! implementations — not just that the formats look similar. The EIP-191
//! envelope (`"\x19Ethereum Signed Message:\n32"`) is the highest-risk
//! divergence point, so its fixture is the most valuable.
//!
//! The post-quantum schemes (Falcon-512, Hawk-512) sign with randomness, so a
//! byte-for-byte artifact fixture isn't meaningful; instead we assert the
//! deterministic parts (identity derivation, PDA, keygen-from-seed
//! reproducibility). A full PQ cross-impl identity golden would need the TS PQ
//! keygen and is left as a follow-up.

use vector_core::{deserialize_artifact, serialize_artifact, verify_artifact, Op, Vector};

/// Round-trip a genuine TS fixture: deserialize, offline-verify, and confirm
/// Rust re-serializes it byte-identically.
fn consumes(fixture: &str) {
    let json = fixture.trim_end();
    let art = deserialize_artifact(json).expect("deserialize TS artifact");
    assert!(
        verify_artifact(&art).expect("known scheme"),
        "TS artifact failed Rust verify"
    );
    assert_eq!(
        serialize_artifact(&art),
        json,
        "Rust re-serialization differs from TS"
    );
}

#[cfg(feature = "ed25519")]
mod ed25519 {
    use super::*;
    use vector_core::Ed25519;
    const FIXTURE: &str = include_str!("fixtures/artifact_ed25519.json");

    #[test]
    fn rust_consumes_a_genuine_ts_artifact() {
        consumes(FIXTURE);
    }

    #[test]
    fn rust_reproduces_the_ts_artifact_bit_for_bit() {
        let v = Vector::new(Ed25519::from_seed(&[7u8; 32]));
        let art = v.authorize(&[0u8; 32], Op::Inert);
        assert_eq!(serialize_artifact(&art), FIXTURE.trim_end());
    }
}

#[cfg(feature = "secp256k1")]
mod secp256k1 {
    use super::*;
    use vector_core::Secp256k1;
    const FIXTURE: &str = include_str!("fixtures/artifact_secp256k1.json");

    #[test]
    fn rust_consumes_a_genuine_ts_artifact() {
        consumes(FIXTURE);
    }

    #[test]
    fn rust_reproduces_the_ts_artifact_bit_for_bit() {
        // RFC-6979 deterministic ECDSA over the same digest => identical bytes.
        let v = Vector::new(Secp256k1::from_seed(&[7u8; 32]));
        let art = v.authorize(&[0u8; 32], Op::Inert);
        assert_eq!(serialize_artifact(&art), FIXTURE.trim_end());
    }
}

#[cfg(feature = "eip191")]
mod eip191 {
    use super::*;
    use vector_core::Eip191;
    const FIXTURE: &str = include_str!("fixtures/artifact_eip191.json");

    #[test]
    fn rust_consumes_a_genuine_ts_artifact() {
        consumes(FIXTURE);
    }

    #[test]
    fn rust_reproduces_the_ts_artifact_bit_for_bit() {
        // Deterministic ECDSA + the EIP-191 personal-sign envelope + recovery
        // byte must all match the TS implementation byte-for-byte.
        let v = Vector::new(Eip191::from_seed(&[7u8; 32]));
        let art = v.authorize(&[0u8; 32], Op::Inert);
        assert_eq!(serialize_artifact(&art), FIXTURE.trim_end());
    }
}

// Post-quantum: deterministic-parts parity (signing itself is randomized).
#[cfg(feature = "hawk512")]
mod hawk512 {
    use vector_core::{hawk512_identity, Hawk512, Signer};

    #[test]
    fn keygen_from_seed_is_reproducible() {
        // Same seed => same wire pubkey => same identity (sha256(wire)).
        let a = Hawk512::from_seed(b"vector-parity-seed");
        let b = Hawk512::from_seed(b"vector-parity-seed");
        assert_eq!(a.wire_pubkey(), b.wire_pubkey());
        assert_eq!(a.identity(), b.identity());
        // identity is exactly sha256(wire pubkey) — the cross-impl-relevant property.
        assert_eq!(a.identity(), hawk512_identity(a.wire_pubkey()).to_vec());
        assert_eq!(a.identity().len(), 32);
    }
}
